#sonarqube:
#        image: git-service.ait.ac.at:8010/ict-caiscluster/logdata-anomaly-miner/aminer-debian
#
#        script:
#                - $(find /opt/ -type f -name sonar-scanner) -Dsonar.projectName=Aminer-Dev -Dsonar.host.url=http://10.103.251.153:9000 -Dsonar.projectKey=deff975a5561d285e315daa894ab291c7bd10a19 -Dsonar.gitlab.max_major_issues_gate=0
#
#sonarqube aecid-testsuite:
#        image: git-service.ait.ac.at:8010/ict-caiscluster/logdata-anomaly-miner/aminer-debian
#        
#        script:
#                - git clone https://gitlab+deploy-token-aecidtestsuite:vu18Eo6k7xfA22vPvorx@git-service.ait.ac.at/ict-caiscluster/aecid-testsuite.git
#                - cd aecid-testsuite
#                - $(find /opt/ -type f -name sonar-scanner) -Dsonar.projectKey=aecid-testsuite -Dsonar.sources=. -Dsonar.host.url=http://10.103.251.153:9000 -Dsonar.login=8d5c9b3e6cc7b6b9c731f02fada0c4d5018f7d34

debian:
        image: git-service.ait.ac.at:8010/ict-caiscluster/logdata-anomaly-miner/aminer-debian

        before_script:
                - service rsyslog start
                - service exim4 start
                - apt install procps -y
                - pip3 install coverage
                - apt install cpulimit -y
                - apt install systemd -y
                - service dbus start

        script:
                -- sendmail root@localhost <<'EOF'
From: "test" <test@test>
To: "test" <root@localhost>
Reply-To: dev@null
Subject: Hello!
Content-Type: text/plain; charset=utf-8

My Mail Content
EOF
                - ansible-playbook /opt/ansible/playbook.yml
                - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.7/dist-packages
                - git clone https://gitlab+deploy-token-aecidtestsuite:vu18Eo6k7xfA22vPvorx@git-service.ait.ac.at/ict-caiscluster/aecid-testsuite.git
                - cp -r /builds/ict-caiscluster/logdata-anomaly-miner/source/root/usr/lib/logdata-anomaly-miner/aminer /builds/ict-caiscluster/logdata-anomaly-miner/aecid-testsuite/aminer
                - cd aecid-testsuite
                - ls -la /var/spool/mail
                - python3 -m unittest unit/events/DefaultMailNotificationEventHandlerTest.py
                - chown -R aminer:aminer /usr/lib/logdata-anomaly-miner
                - chown -h aminer:aminer /usr/bin/AMiner
                - chmod +x /usr/lib/logdata-anomaly-miner/AMiner
                - python3 -m unittest discover -s unit -p '*Test.py'
                - rm /var/mail/mail
                - cp demo/AMiner/demo-config.py /tmp
                - chown -R aminer:aminer /tmp/lib
                - chown aminer:aminer /tmp/AMinerRemoteLog.txt
                - chmod +x demo/AMiner/aminerDemo.sh
                - ./demo/AMiner/aminerDemo.sh > /tmp/demo
                - cd integration
                - cp config* /tmp
                - chmod +x aminerIntegrationTest.sh
                - chmod +x aminerIntegrationTest2.sh
                - chown aminer:aminer /tmp/AMinerRemoteLog.txt
                - ./aminerIntegrationTest.sh
                - ./aminerIntegrationTest2.sh
                - rm /var/mail/mail
                - cd ..
                - coverage run --source=./aminer -m unittest discover -s unit -p '*Test.py'
                - touch /tmp/report
                - echo 'Statement Coverage:' > /tmp/report
                - coverage report >> /tmp/report
                - coverage run --source=./aminer --branch -m unittest discover -s unit -p '*Test.py'
                - echo 'Branch Coverage:' >> /tmp/report
                - coverage report >> /tmp/report
                - cat /tmp/report
                
        after_script:
                - sleep 15
                - ls -la /var/spool/mail
                - ls -la /var/mail
                - cat /var/mail/root

ubuntu:
        image: git-service.ait.ac.at:8010/ict-caiscluster/logdata-anomaly-miner/aminer-ubuntu
        
        before_script:
                - service rsyslog start
                - service exim4 start
                - pip3 install coverage
                - apt install cpulimit -y
                - apt install systemd -y
                - service dbus start
                - ln -s /usr/local/lib/python3.6/dist-packages/pytz /usr/lib/python3/dist-packages/pytz
                - ln -s /usr/local/lib/python3.6/dist-packages/pytz /usr/lib/python3.6/pytz
                - ln -s /usr/local/lib/python3.6/dist-packages/pytz /usr/lib/python3.7/pytz
                - ln -s /usr/local/lib/python3.6/dist-packages/pytz /usr/lib/python3.8/pytz
        
        script:
                - ansible-playbook /opt/ansible/playbook.yml
                - find / -xdev 2>/dev/null -name "python3.*"
                - find / -xdev 2>/dev/null -name "python3"
                - find / -xdev 2>/dev/null -name "pytz*"
                - runuser -u aminer -- pip3 install pytz
                - runuser -u root -- pip3 install pytz
                - git clone https://gitlab+deploy-token-aecidtestsuite:vu18Eo6k7xfA22vPvorx@git-service.ait.ac.at/ict-caiscluster/aecid-testsuite.git
                - cp -r /builds/ict-caiscluster/logdata-anomaly-miner/source/root/usr/lib/logdata-anomaly-miner/aminer /builds/ict-caiscluster/logdata-anomaly-miner/aecid-testsuite/aminer
                - cd aecid-testsuite
                ##########
                - mkdir /tmp/lib 2> /dev/null
                - mkdir /tmp/lib/aminer 2> /dev/null
                - chown -R aminer:aminer /tmp/lib
                - cp demo/AMiner/demo-config.py /tmp
                - chmod +x /usr/lib/logdata-anomaly-miner/AMiner
                - chmod +x demo/AMiner/aminerDemo.sh
                - ./demo/AMiner/aminerDemo.sh > /tmp/demo
                ##########
                - python3 -m unittest unit/events/DefaultMailNotificationEventHandlerTest.py
                - chown -R aminer:aminer /usr/lib/logdata-anomaly-miner
                - chown -h aminer:aminer /usr/bin/AMiner
                - chmod +x /usr/lib/logdata-anomaly-miner/AMiner
                - python3 -m unittest discover -s unit -p '*Test.py'
                - cp demo/AMiner/demo-config.py /tmp
                - chmod +x demo/AMiner/aminerDemo.sh
                - chown -R aminer:aminer /tmp/lib
                - chown aminer:aminer /tmp/AMinerRemoteLog.txt
                - ./demo/AMiner/aminerDemo.sh > /tmp/demo
                - cd integration
                - cp config* /tmp
                - chmod +x aminerIntegrationTest.sh
                - chmod +x aminerIntegrationTest2.sh
                - chown aminer:aminer /tmp/AMinerRemoteLog.txt
                - ./aminerIntegrationTest.sh
                - ./aminerIntegrationTest2.sh
                - rm /var/mail/mail
                - cd ..
                - coverage run --source=./aminer -m unittest discover -s unit -p '*Test.py'
                - touch /tmp/report
                - echo 'Statement Coverage:' > /tmp/report
                - coverage report >> /tmp/report
                - coverage run --source=./aminer --branch -m unittest discover -s unit -p '*Test.py'
                - echo 'Branch Coverage:' >> /tmp/report
                - coverage report >> /tmp/report
                - cat /tmp/report
                
